import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Apple iPhone 14',
    price: 999,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-model-unselect-gallery-2-202209?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1660753617559',
    description: 'The latest iPhone with A16 Bionic chip and advanced camera system',
    category: 'Smartphones',
    rating: 4.8,
    delivery: 'Free Shipping',
  },
  {
    id: '2',
    name: 'Samsung Galaxy S22',
    price: 799,
    image: 'https://images.samsung.com/is/image/samsung/US-GALAXY-S22-ULTRA-5G-BUY-220207-1920x1280-1-220207',
    description: 'Powerful Android smartphone with pro-grade camera',
    category: 'Smartphones',
    rating: 4.7,
    delivery: 'Standard Shipping',
  },
  {
    id: '3',
    name: 'Sony WH-1000XM5',
    price: 349,
    image: 'https://m.media-amazon.com/images/I/61XZQXFQeVL._AC_SL1500_.jpg',
    description: 'Industry-leading noise cancellation headphones',
    category: 'Audio',
    rating: 4.9,
    delivery: 'Express Shipping',
  },
  {
    id: '4',
    name: 'Dell XPS 13',
    price: 1199,
    image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9315/media-gallery/notebook-xps-9315-nt-blue-gallery-1.psd?$flex_2$&wid=2000&hei=2000',
    description: 'Ultra-thin laptop with stunning InfinityEdge display',
    category: 'Laptops',
    rating: 4.8,
    delivery: 'Free Shipping',
  },
  {
    id: '5',
    name: 'Apple Watch Series 8',
    price: 399,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MP0C3ref_VW_34FR+watch-45-alum-midnight-nc-8s_VW_34FR_WF_CO?wid=2000&hei=2000&fmt=jpeg&qlt=90&.v=1661471047837',
    description: 'Advanced health monitoring and fitness tracking',
    category: 'Wearables',
    rating: 4.7,
    delivery: 'Free Shipping',
  },
];
